#!/bin/bash

SOURCE_DIR=$1
BUILD_DIR=$2
INSTALL_DIR=$3

BUILD_TYPE=RelWithDebInfo
[[ ! -z $4 ]] && BUILD_TYPE=$4

cmake \
  -G Ninja \
  -S ${SOURCE_DIR} \
  -B ${BUILD_DIR} \
  -DCMAKE_EXPORT_COMPILE_COMMANDS=On \
  -DLLVM_INSTALL_UTILS=On \
  -DCMAKE_BUILD_TYPE=${BUILD_TYPE} \
  -DBUILD_SHARED_LIBS=On \
  -DLLVM_ENABLE_Z3_SOLVER=Off \
  -DLLVM_ENABLE_ASSERTIONS=On \
  -DLLVM_TARGETS_TO_BUILD="X86;AArch64" \
  -DLLVM_ENABLE_SPHINX=Off \
  -DLLVM_INSTALL_UTILS=On \
  -DLLVM_OPTIMIZED_TABLEGEN=On \
  -DLLVM_ENABLE_PROJECTS="clang" \
  -DLLVM_CCACHE_BUILD=On \
  -DCMAKE_INSTALL_PREFIX="${INSTALL_DIR}"
