#!/bin/bash

INSTALL_DIR=/usr/local/llvm-9/toolchain/

cmake \
  -G Ninja \
  -DBUILD_SHARED_LIBS=On \
  -DLLVM_ENABLE_ASSERTIONS=On \
  -DLLVM_TARGETS_TO_BUILD="X86;AArch64" \
  -DLLVM_ENABLE_SPHINX=Off \
  -DLLVM_ENABLE_THREADS=On \
  -DLLVM_INSTALL_UTILS=On \
  -DLIBCXX_ENABLE_EXCEPTIONS=On \
  -DLIBCXX_ENABLE_RTTI=On \
  -DLLVM_OPTIMIZED_TABLEGEN=On \
  -DLLVM_PARALLEL_LINK_JOBS=6 \
  -DLLVM_UNIFICO_TABLEGEN_FEATURES="-DUNIFICO_GPR_CALLING_CONV;-DUNIFICO_FPR_CALLING_CONV;-DUNIFICO_REGALLOC_RULES;-DUNIFICO_REMAT_RULES;-DUNIFICO_REG_COST;-DUNIFICO_AARCH64_TWOADDR;-DUNIFICO_INSTR_EXTENSION;-DUNIFICO_CHEAP_MOVES" \
  -DLLVM_ENABLE_PROJECTS="clang" \
  -DCMAKE_BUILD_TYPE=RelWithDebInfo \
  -DCMAKE_INSTALL_PREFIX="${INSTALL_DIR}" \
  "/code/llvm-unifico/llvm"
